import { useState, useEffect } from 'react';
import { 
  Play, 
  Download, 
  CheckCircle, 
  Loader2, 
  Package, 
  Terminal,
  FileText,
  Zap,
  Settings,
  AlertCircle
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { toast } from '@/hooks/use-toast';

interface EnvironmentConfig {
  name: string;
  version: string;
  dependencies: string[];
  devDependencies: string[];
  scripts: Record<string, string>;
  files: { name: string; content: string }[];
  runtime: string;
  linting: string[];
  formatting: string[];
}

interface EnvironmentSetupProps {
  selectedStack: string;
  selectedLanguage: string;
  onEnvironmentReady: (config: EnvironmentConfig) => void;
  onFilesGenerated: (files: Array<{ name: string; content: string; language: string }>) => void;
}

const environmentConfigs: Record<string, EnvironmentConfig> = {
  react: {
    name: 'React + TypeScript',
    version: '18.2.0',
    dependencies: ['react', 'react-dom', 'typescript', '@types/react', '@types/react-dom'],
    devDependencies: ['vite', '@vitejs/plugin-react', 'eslint', 'prettier', 'tailwindcss'],
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
      lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0'
    },
    files: [
      {
        name: 'App.tsx',
        content: `import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to React + TypeScript</h1>
        <p>Start building your amazing app!</p>
      </header>
    </div>
  );
}

export default App;`
      },
      {
        name: 'main.tsx',
        content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`
      }
    ],
    runtime: 'Node.js 18+',
    linting: ['ESLint', 'TypeScript'],
    formatting: ['Prettier']
  },
  nextjs: {
    name: 'Next.js Full-Stack',
    version: '14.0.0',
    dependencies: ['next', 'react', 'react-dom', 'typescript', '@types/node'],
    devDependencies: ['eslint', 'eslint-config-next', 'tailwindcss', 'postcss', 'autoprefixer'],
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    files: [
      {
        name: 'page.tsx',
        content: `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm">
        <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
        <p className="mt-4 text-lg">Start building your full-stack application!</p>
      </div>
    </main>
  )
}`
      },
      {
        name: 'layout.tsx',
        content: `import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create-next-app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`
      }
    ],
    runtime: 'Node.js 18+',
    linting: ['ESLint', 'Next.js'],
    formatting: ['Prettier']
  },
  python: {
    name: 'Python + FastAPI',
    version: '3.9+',
    dependencies: ['fastapi', 'uvicorn', 'pydantic', 'sqlalchemy', 'alembic'],
    devDependencies: ['pytest', 'black', 'flake8', 'mypy'],
    scripts: {
      dev: 'uvicorn main:app --reload',
      start: 'uvicorn main:app --host 0.0.0.0 --port 8000',
      test: 'pytest',
      format: 'black .'
    },
    files: [
      {
        name: 'main.py',
        content: `from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="My API", version="1.0.0")

class Item(BaseModel):
    name: str
    description: str = None
    price: float

@app.get("/")
async def root():
    return {"message": "Hello World"}

@app.post("/items/")
async def create_item(item: Item):
    return {"item": item, "message": "Item created successfully"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`
      },
      {
        name: 'requirements.txt',
        content: `fastapi==0.104.1
uvicorn[standard]==0.24.0
pydantic==2.5.0
sqlalchemy==2.0.23
alembic==1.12.1`
      }
    ],
    runtime: 'Python 3.9+',
    linting: ['Flake8', 'MyPy'],
    formatting: ['Black']
  },
  express: {
    name: 'Express.js API',
    version: '4.18.0',
    dependencies: ['express', 'cors', 'helmet', 'morgan', 'dotenv'],
    devDependencies: ['nodemon', 'eslint', 'prettier', '@types/express', 'typescript'],
    scripts: {
      dev: 'nodemon src/server.ts',
      build: 'tsc',
      start: 'node dist/server.js',
      lint: 'eslint src --ext .ts'
    },
    files: [
      {
        name: 'server.ts',
        content: `import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(helmet());
app.use(cors());
app.use(morgan('combined'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Routes
app.get('/', (req, res) => {
  res.json({ message: 'Welcome to Express.js API' });
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// Start server
app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});`
      },
      {
        name: 'package.json',
        content: `{
  "name": "express-api",
  "version": "1.0.0",
  "description": "Express.js API server",
  "main": "dist/server.js",
  "scripts": {
    "dev": "nodemon src/server.ts",
    "build": "tsc",
    "start": "node dist/server.js"
  },
  "dependencies": {
    "express": "^4.18.0",
    "cors": "^2.8.5",
    "helmet": "^7.0.0",
    "morgan": "^1.10.0",
    "dotenv": "^16.3.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.0",
    "typescript": "^5.0.0",
    "@types/express": "^4.17.0"
  }
}`
      }
    ],
    runtime: 'Node.js 16+',
    linting: ['ESLint', 'TypeScript'],
    formatting: ['Prettier']
  }
};

export const EnvironmentSetup = ({ 
  selectedStack, 
  selectedLanguage, 
  onEnvironmentReady, 
  onFilesGenerated 
}: EnvironmentSetupProps) => {
  const [isSettingUp, setIsSettingUp] = useState(false);
  const [setupProgress, setSetupProgress] = useState(0);
  const [setupStep, setSetupStep] = useState('');
  const [isComplete, setIsComplete] = useState(false);
  const [setupError, setSetupError] = useState<string | null>(null);

  const config = environmentConfigs[selectedStack] || environmentConfigs.react;

  const setupSteps = [
    'Initializing environment...',
    'Installing dependencies...',
    'Configuring linting rules...',
    'Setting up formatting...',
    'Generating starter files...',
    'Configuring build tools...',
    'Environment ready!'
  ];

  const setupEnvironment = async () => {
    setIsSettingUp(true);
    setSetupProgress(0);
    setSetupError(null);
    setIsComplete(false);

    try {
      for (let i = 0; i < setupSteps.length; i++) {
        setSetupStep(setupSteps[i]);
        setSetupProgress((i / (setupSteps.length - 1)) * 100);
        
        // Simulate setup time
        await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 400));
      }

      // Generate files based on selected stack
      const generatedFiles = config.files.map(file => ({
        name: file.name,
        content: file.content,
        language: getLanguageFromFileName(file.name)
      }));

      onEnvironmentReady(config);
      onFilesGenerated(generatedFiles);
      setIsComplete(true);
      
      toast({
        title: "Environment ready!",
        description: `${config.name} environment has been configured successfully.`,
      });
    } catch (error) {
      setSetupError('Failed to setup environment. Please try again.');
      console.error('Environment setup error:', error);
    } finally {
      setIsSettingUp(false);
    }
  };

  const getLanguageFromFileName = (fileName: string): string => {
    const ext = fileName.split('.').pop()?.toLowerCase();
    switch (ext) {
      case 'ts': case 'tsx': return 'typescript';
      case 'js': case 'jsx': return 'javascript';
      case 'py': return 'python';
      case 'css': return 'css';
      case 'html': return 'html';
      case 'json': return 'json';
      case 'md': return 'markdown';
      default: return 'plaintext';
    }
  };

  const resetSetup = () => {
    setIsComplete(false);
    setSetupError(null);
    setSetupProgress(0);
    setSetupStep('');
  };

  useEffect(() => {
    resetSetup();
  }, [selectedStack, selectedLanguage]);

  return (
    <Card className="w-full">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm flex items-center gap-2">
          <Zap className="h-4 w-4 text-primary" />
          Auto Environment Setup
          <Badge variant="secondary" className="text-xs">
            {config.name}
          </Badge>
        </CardTitle>
      </CardHeader>
      
      <CardContent className="space-y-4">
        {setupError && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{setupError}</AlertDescription>
          </Alert>
        )}

        {!isComplete && !isSettingUp && (
          <div className="space-y-3">
            <div className="text-sm text-muted-foreground">
              Click to automatically configure your {config.name} environment with all necessary dependencies and tools.
            </div>
            
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div>
                <div className="font-medium mb-1">Runtime:</div>
                <Badge variant="outline" className="text-xs">{config.runtime}</Badge>
              </div>
              <div>
                <div className="font-medium mb-1">Dependencies:</div>
                <Badge variant="outline" className="text-xs">{config.dependencies.length} packages</Badge>
              </div>
            </div>

            <Button 
              onClick={setupEnvironment}
              className="w-full"
              disabled={isSettingUp}
            >
              <Play className="h-4 w-4 mr-2" />
              Setup Environment
            </Button>
          </div>
        )}

        {isSettingUp && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span className="text-sm">{setupStep}</span>
            </div>
            <Progress value={setupProgress} className="w-full" />
            <div className="text-xs text-muted-foreground">
              {Math.round(setupProgress)}% complete
            </div>
          </div>
        )}

        {isComplete && (
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-green-600">
              <CheckCircle className="h-4 w-4" />
              <span className="text-sm font-medium">Environment Ready!</span>
            </div>
            
            <div className="grid grid-cols-1 gap-2 text-xs">
              <div className="flex items-center gap-2">
                <Package className="h-3 w-3" />
                <span>{config.dependencies.length + config.devDependencies.length} packages installed</span>
              </div>
              <div className="flex items-center gap-2">
                <FileText className="h-3 w-3" />
                <span>{config.files.length} starter files generated</span>
              </div>
              <div className="flex items-center gap-2">
                <Settings className="h-3 w-3" />
                <span>Linting & formatting configured</span>
              </div>
            </div>

            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={resetSetup}>
                Reset
              </Button>
              <Button variant="outline" size="sm" className="flex-1">
                <Terminal className="h-3 w-3 mr-1" />
                Open Terminal
              </Button>
            </div>
          </div>
        )}

        {/* Environment Details */}
        <div className="border-t pt-3 space-y-2">
          <div className="text-xs font-medium">Included Tools:</div>
          <div className="flex flex-wrap gap-1">
            {config.linting.map((tool, index) => (
              <Badge key={index} variant="secondary" className="text-xs">
                {tool}
              </Badge>
            ))}
            {config.formatting.map((tool, index) => (
              <Badge key={index} variant="secondary" className="text-xs">
                {tool}
              </Badge>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};